services:
  moodle:
    image: brandkern/moodle:4.5-latest
    container_name: moodle
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      DB_HOST: db
      DB_NAME: moodle
      DB_USER: moodleuser
      DB_PASS: moodlepass
      WWWROOT: http://localhost:8080
    volumes:
      - moodledata:/var/www/moodledata
      - moodlehtml:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb:11.3
    container_name: moodle-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodleuser
      MYSQL_PASSWORD: moodlepass
    volumes:
      - dbdata:/var/lib/mysql

  moodle-cron:
    image: brandkern/moodle:4.5-latest
    container_name: moodle-cron
    restart: unless-stopped
    depends_on:
      - moodle
    volumes:
      - moodledata:/var/www/moodledata
      - moodlehtml:/var/www/html
    environment:
      DB_HOST: db
      DB_NAME: moodle
      DB_USER: moodleuser
      DB_PASS: moodlepass
    entrypoint: ["/cron.sh"]

volumes:
  moodledata:
  moodlehtml:
  dbdata:

